### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by odigity** [nov/openid_connect#24]
Are there no docs for this gem other than the two sample apps' code?

I've looked at the READMEs and doc/ folder in this repo and the repo for the two sample apps, as well as the autogenerated library docs at rdoc.info, and I cannot find one scrap of documentation.

This is the only maintained gem that implements OpenID Connect that I can find, and the two demo apps prove that the gem works and is interoperable with itself, which is great.

But I have no idea how to use it...

**Comment by odigity** [comment]
Ok, I just noticed there's some content in the wiki for this repo:

https://github.com/nov/openid_connect/wiki

But the Server side of things has a note:

"will write someday.."

:)

**Comment by gbirchmeier** [comment]
Yes, as an educational example, this could be better.

I'm attempting to run the two examples against each other locally so I can see the requests they receive, and I can't even get the RP to discover the OP.  It just times out.

**Comment by kaibadash** [comment]
@gbirchmeier 
Did you check issuer setting in config/connect/id_token/issuer.yml.
Here is my example.

```
development: &defaults
  issuer: http://localhost:3000

test:
  <<: *defaults

production:
  <<: *defaults
  issuer: http://localhost:3000
```
